QUESTIONS = [
('What is the level of RNA expression?', ('None', 'Low', 'Moderate', 'High')),
('What is the level of protein expression?', ('None', 'Low', 'Moderate', 'High')),
('What is the distribution of expression?', ('Ilan1', 'Ilan2', 'Ilan3')),
('What patterns does the RNA make?', ('Evenly scattered', 'Single transcripts', 'Nuclear', 'Transcription foci', 'More in some cells than others', 'Other')),
('What patterns does the protein make?', ('Punctate', 'Nuclear', 'Cell edges', 'Muscle fibres', 'Diffuse', 'Other')),
('Nascent transcript level', ('None', 'Low', 'Moderate', 'High')),
('Cytosolic RNA level', ('None', 'Low', 'Moderate', 'High')),
('Is there obvious RNA/protein discordance (whole image)?', ('No', 'Yes')),
('Flag this gene as a potential one to use for a figure in the paper?', ''),
('General comments', ''),
('Is RNA present in NBs?', ('Yes', 'No')),
('Is protein present in NBs?', ('Yes', 'No')),
('Is RNA present in anlagen?', ('Yes', 'No')),
('Is protein present in anlagen?', ('Yes', 'No')),
('Is RNA present in other cells?', ('Yes', 'No')),
('Is protein present in other cells?', ('Yes', 'No')),
('Is RNA distribution cell-type specific?', ('NBs', 'Anlagen', 'Other cells')),
('Is protein distribution cell-type specific?', ('NBs', 'Anlagen', 'Other cells')),
]
